# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Documents/Basys3_Master.xdc

# IP: ip/blk_mem_gen_arb/blk_mem_gen_arb.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_arb || ORIG_REF_NAME==blk_mem_gen_arb}]

# IP: ip/dds_compiler_0/dds_compiler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0}]

# XDC: ip/blk_mem_gen_arb/blk_mem_gen_arb_ooc.xdc
