# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/sidxb/FPGA/ee2020/ee2020.cache/wt [current_project]
set_property parent.project_path C:/Users/sidxb/FPGA/ee2020/ee2020.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/sidxb/FPGA/ee2020/ee2020.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/ip/arb.coe
read_verilog -library xil_defaultlib {
  C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/new/uart.v
  C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/new/var_clock.v
  C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/new/vga.v
  C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/new/triangle.v
  C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/new/square.v
  C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/new/sine.v
  C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/new/arb.v
  C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/imports/new/seg_disp.v
  C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/new/debounce.v
  C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/new/main.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/imports/hdl/Ps2Interface.vhd
  C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/imports/Downloads/DA2RefComp.vhd
  C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/imports/hdl/MouseCtl.vhd
}
read_ip -quiet C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/ip/blk_mem_gen_arb/blk_mem_gen_arb.xci
set_property used_in_implementation false [get_files -all c:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/ip/blk_mem_gen_arb/blk_mem_gen_arb_ooc.xdc]
set_property is_locked true [get_files C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/ip/blk_mem_gen_arb/blk_mem_gen_arb.xci]

read_ip -quiet C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci
set_property is_locked true [get_files C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/constrs_1/imports/Documents/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/sidxb/FPGA/ee2020/ee2020.srcs/constrs_1/imports/Documents/Basys3_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top myDAC -part xc7a35tcpg236-1 -directive AreaOptimized_medium -control_set_opt_threshold 1


write_checkpoint -force -noxdef myDAC.dcp

catch { report_utilization -file myDAC_utilization_synth.rpt -pb myDAC_utilization_synth.pb }
